/* =========================================================================
   OGÓLNA BAZA SKINÓW — WSPÓLNY PLIK
   -------------------------------------------------------------------------
   Szeroka pula przedmiotów (weapon/skin/wear/price) niezwiązana z żadną
   konkretną skrzynką, używana wszędzie tam, gdzie trzeba dobrać przedmiot
   (albo kilka) o konkretnej wartości - np. "połowa wygranej puli" w bitwie
   2v2 (battle.html) albo nagroda za osiągnięcie poziomu (equipment.html).
   ========================================================================= */
const GENERAL_SKIN_DB = [
  {weapon:"MP5-SD", skin:"Co-Processor", wear:"MW", price:0.92},
  {weapon:"P90", skin:"Grim", wear:"FT", price:1.12},
  {weapon:"AUG", skin:"Triqua", wear:"FT", price:1.16},
  {weapon:"Tec-9", skin:"Fubar", wear:"FT", price:1.2},
  {weapon:"Glock-18", skin:"Off World", wear:"FT", price:1.24},
  {weapon:"UMP-45", skin:"Labyrinth", wear:"FT", price:1.28},
  {weapon:"USP-S", skin:"Check Engine", wear:"FT", price:1.32},
  {weapon:"P90", skin:"Facility Negative", wear:"MW", price:1.4},
  {weapon:"FAMAS", skin:"Survivor Z", wear:"FT", price:1.56},
  {weapon:"MAC-10", skin:"Classic Crate", wear:"FT", price:1.6},
  {weapon:"G3SG1", skin:"Orange Crash", wear:"FT", price:1.64},
  {weapon:"Five-SeveN", skin:"Capillary", wear:"FT", price:1.64},
  {weapon:"P250", skin:"Valence", wear:"FT", price:1.68},
  {weapon:"SSG 08", skin:"Abyss", wear:"FT", price:1.72},
  {weapon:"Desert Eagle", skin:"Oxide Blaze", wear:"FT", price:1.72},
  {weapon:"Desert Eagle", skin:"Urban Rubble", wear:"FT", price:1.84},
  {weapon:"SG 553", skin:"Aerial", wear:"WW", price:1.84},
  {weapon:"MP7", skin:"Akoben", wear:"FT", price:1.88},
  {weapon:"SCAR-20", skin:"Blueprint", wear:"MW", price:1.88},
  {weapon:"PP-Bizon", skin:"Jungle Slipstream", wear:"FT", price:1.96},
  {weapon:"UMP-45", skin:"Arctic Wolf", wear:"FT", price:2.16},
  {weapon:"M4A1-S", skin:"Nitro", wear:"FT", price:2.16},
  {weapon:"G3SG1", skin:"Orange Crash", wear:"FN", price:2.2},
  {weapon:"M249", skin:"System Lock", wear:"WW", price:2.2},
  {weapon:"UMP-45", skin:"Briefing", wear:"MW", price:2.32},
  {weapon:"MP7", skin:"Urban Hazard", wear:"FN", price:2.32},
  {weapon:"MAG-7", skin:"SWAG-7", wear:"FT", price:2.32},
  {weapon:"Glock-18", skin:"Catacombs", wear:"FT", price:2.36},
  {weapon:"Desert Eagle", skin:"Urban Rubble", wear:"WW", price:2.64},
  {weapon:"Glock-18", skin:"Warhawk", wear:"MW", price:2.72},
  {weapon:"Tec-9", skin:"Ice Cap", wear:"MW", price:2.84},
  {weapon:"Five-SeveN", skin:"Scumbria", wear:"BS", price:2.92},
  {weapon:"P2000", skin:"Oceanic", wear:"FT", price:3.16},
  {weapon:"MP7", skin:"Cirrus", wear:"FT", price:3.2},
  {weapon:"USP-S", skin:"Torque", wear:"FT", price:3.2},
  {weapon:"Tec-9", skin:"Jambiya", wear:"FT", price:3.28},
  {weapon:"R8 Revolver", skin:"Crimson Web", wear:"BS", price:3.84},
  {weapon:"AWP", skin:"Pit Viper", wear:"FT", price:3.92},
  {weapon:"Glock-18", skin:"Moonrise", wear:"FT", price:4.04},
  {weapon:"CZ75-Auto", skin:"Tacticat", wear:"FT", price:4.08},
  {weapon:"UMP-45", skin:"Exposure", wear:"FT", price:4.08},
  {weapon:"Glock-18", skin:"Bunsen Burner", wear:"FT", price:4.32},
  {weapon:"Galil AR", skin:"Rocket Pop", wear:"FT", price:5},
  {weapon:"Glock-18", skin:"Weasel", wear:"FT", price:5.28},
  {weapon:"CZ75-Auto", skin:"Pole Position", wear:"FT", price:5.4},
  {weapon:"SSG 08", skin:"Ghost Crusader", wear:"FT", price:6.04},
  {weapon:"AK-47", skin:"Elite Build", wear:"WW", price:6.4},
  {weapon:"AWP", skin:"Pit Viper", wear:"MW", price:6.52},
  {weapon:"Glock-18", skin:"Moonrise", wear:"MW", price:7},
  {weapon:"SSG 08", skin:"Slashed", wear:"WW", price:7.36},
  {weapon:"P90", skin:"Elite Build", wear:"FT", price:7.76},
  {weapon:"P90", skin:"Chopper", wear:"MW", price:8.04},
  {weapon:"P250", skin:"Wingshot", wear:"FT", price:8.12},
  {weapon:"Glock-18", skin:"Weasel", wear:"MW", price:8.36},
  {weapon:"AK-47", skin:"Elite Build", wear:"FT", price:8.48},
  {weapon:"FAMAS", skin:"Hexane", wear:"FT", price:8.52},
  {weapon:"P90", skin:"Chopper", wear:"FT", price:8.6},
  {weapon:"CZ75-Auto", skin:"Tigris", wear:"FT", price:9.44},
  {weapon:"P250", skin:"Supernova", wear:"FT", price:9.64},
  {weapon:"CZ75-Auto", skin:"Pole Position", wear:"MW", price:10},
  {weapon:"AWP", skin:"Worm God", wear:"FT", price:10.2},
  {weapon:"AWP", skin:"Phobos", wear:"FT", price:10.44},
  {weapon:"Five-SeveN", skin:"Urban Hazard", wear:"MW", price:10.84},
  {weapon:"MAC-10", skin:"Ultraviolet", wear:"FT", price:11.48},
  {weapon:"AWP", skin:"Worm God", wear:"MW", price:12},
  {weapon:"Galil AR", skin:"Stone Cold", wear:"FT", price:12.08},
  {weapon:"CZ75-Auto", skin:"Tigris", wear:"MW", price:13.6},
  {weapon:"AK-47", skin:"Emerald Pinstripe", wear:"FT", price:14.24},
  {weapon:"USP-S", skin:"Guardian", wear:"MW", price:14.4},
  {weapon:"Tec-9", skin:"Sandstorm", wear:"MW", price:14.64},
  {weapon:"M4A4", skin:"Evil Daimyo", wear:"FT", price:15.76},
  {weapon:"M4A1-S", skin:"Flashback", wear:"WW", price:15.76},
  {weapon:"USP-S", skin:"Cyrex", wear:"FT", price:15.96},
  {weapon:"M4A1-S", skin:"Flashback", wear:"FT", price:16.52},
  {weapon:"M4A1-S", skin:"Briefing", wear:"FT", price:19},
  {weapon:"M4A4", skin:"Griffin", wear:"FT", price:20.76},
  {weapon:"USP-S", skin:"Cyrex", wear:"MW", price:21.32},
  {weapon:"M4A1-S", skin:"Blood Tiger", wear:"MW", price:23.52},
  {weapon:"CZ75-Auto", skin:"Hexane", wear:"FN", price:24.56},
  {weapon:"Tec-9", skin:"Isaac", wear:"MW", price:24.72},
  {weapon:"USP-S", skin:"Guardian", wear:"FN", price:33.84},
  {weapon:"M4A1-S", skin:"Basilisk", wear:"FT", price:41.44},
  {weapon:"M4A1-S", skin:"Basilisk", wear:"MW", price:45.36},
  {weapon:"Desert Eagle", skin:"Crimson Web", wear:"FT", price:56.72},
  {weapon:"Five-SeveN", skin:"Case Hardened", wear:"FT", price:66.84},
  {weapon:"AK-47", skin:"Blue Laminate", wear:"FT", price:75.92},
  {weapon:"MAC-10", skin:"Amber Fade", wear:"MW", price:76.32},
  {weapon:"USP-S", skin:"Overgrowth", wear:"FT", price:101.48},
  {weapon:"AK-47", skin:"Orbit Mk01", wear:"FT", price:125.28},
  {weapon:"Tec-9", skin:"Toxic", wear:"FT", price:126.84},
  {weapon:"FAMAS", skin:"Styx", wear:"MW", price:148.8},
  {weapon:"AWP", skin:"Pink DDPAT", wear:"FT", price:169.2},
  {weapon:"MP9", skin:"Setting Sun", wear:"FT", price:177.08},
  {weapon:"M4A1-S", skin:"Bright Water", wear:"FT", price:184.16},
  {weapon:"M4A1-S", skin:"Dark Water", wear:"FT", price:326.68},
  {weapon:"Five-SeveN", skin:"Crimson Blossom", wear:"MW", price:433.52},
  {weapon:"MAC-10", skin:"Fade", wear:"FN", price:556.28},
  {weapon:"MAG-7", skin:"Counter Terrace", wear:"MW", price:811.72},
  {weapon:"Galil AR", skin:"Aqua Terrace", wear:"FT", price:842.52},
  {weapon:"M4A1-S", skin:"Icarus Fell", wear:"FN", price:2524.28},
  {weapon:"Desert Eagle", skin:"Sunset Storm 弐", wear:"FT", price:2778.76},
  {weapon:"Desert Eagle", skin:"Blaze", wear:"FN", price:3813.77},
  {weapon:"Karambit", skin:"Tiger Tooth", wear:"FN", price:5366.53},
  {weapon:"Sport Gloves", skin:"Slingshot", wear:"MW", price:5734.74},
  {weapon:"Glock-18", skin:"Fade", wear:"FN", price:8584.12},
  {weapon:"Talon Knife", skin:"Doppler Ruby", wear:"FN", price:17062.91},
  {weapon:"M4A4", skin:"Howl", wear:"FN", price:37641.28},
];
