/* =========================================================================
   ŹRÓDŁA OBRAZKÓW SKINÓW — WSPÓLNY PLIK
   -------------------------------------------------------------------------
   Ten plik jest wczytywany przez case_simulator.html i case_restricted.html
   (oraz każdy inny plik skrzynki, który go podepnie) zamiast trzymania
   linku do obrazka osobno w każdym przedmiocie tablicy ITEMS.

   JAK DODAĆ WŁASNE OBRAZKI:
   Wklej link (URL) lub ścieżkę do lokalnego pliku jako wartość klucza
   "Broń|Skin|Wear", np:
       "AK-47|Blue Laminate|FT": "https://example.com/ak47_blue_laminate.png",
   Klucze są posortowane alfabetycznie (broń, potem skin, potem wear) —
   zachowaj tę kolejność przy dodawaniu nowych pozycji, żeby łatwo było
   je odnaleźć.
   Puste pole ("") oznacza brak obrazka — pokaże się zastępczy napis.
   ========================================================================= */

const SKIN_IMAGES = {
  "AK-47|Aquamarine Revenge|FN": "https://cdn.g4skins.com/items/730_2/ak-47-aquamarine-revenge-(factory-new).png?v=4",
  "AK-47|B the Monster|FN": "https://cdn.g4skins.com/items/730_2/ak-47-b-the-monster-(factory-new).png?v=4",
  "AK-47|B the Monster|MW": "https://cdn.g4skins.com/items/730_2/ak-47-b-the-monster-(minimal-wear).png?v=4",
  "AK-47|Blue Laminate|FT": "https://cdn.g4skins.com/items/730_2/ak-47-blue-laminate-(field-tested).png?v=4",
  "AK-47|Elite Build|FT": "https://cdn.g4skins.com/items/730_2/ak-47-elite-build-(field-tested).png?v=4",
  "AK-47|Elite Build|WW": "https://cdn.g4skins.com/items/730_2/ak-47-elite-build-(well-worn).png?v=4",
  "AK-47|Emerald Pinstripe|FT": "https://cdn.g4skins.com/items/730_2/ak-47-emerald-pinstripe-(field-tested).png?v=4",
  "AK-47|Frontside Misty|WW": "https://cdn.g4skins.com/items/730_2/ak-47-frontside-misty-(well-worn).png?v=4",
  "AK-47|Gold Arabesque|FN": "https://cdn.g4skins.com/items/730_2/ak-47-gold-arabesque-(factory-new).png?v=4",
  "AK-47|Hydroponic|FN": "https://cdn.g4skins.com/items/730_2/ak-47-hydroponic-(factory-new).png?v=4",
  "AK-47|Inheritance|FT": "https://cdn.g4skins.com/items/730_2/ak-47-inheritance-(field-tested).png?v=4",
  "AK-47|Jaguar|FN": "https://cdn.g4skins.com/items/730_2/ak-47-jaguar-(factory-new).png?v=4",
  "AK-47|Neon Rider|MW": "https://cdn.g4skins.com/items/730_2/ak-47-neon-rider-(minimal-wear).png?v=4",
  "AK-47|Nouveau Rouge|WW": "https://cdn.g4skins.com/items/730_2/ak-47-nouveau-rouge-(well-worn).png?v=4",
  "AK-47|Orbit Mk01|FT": "https://cdn.g4skins.com/items/730_2/ak-47-orbit-mk01-(field-tested).png?v=4",
  "AK-47|Point Disarray|FT": "https://cdn.g4skins.com/items/730_2/ak-47-point-disarray-(field-tested).png?v=4",
  "AK-47|Point Disarray|WW": "https://cdn.g4skins.com/items/730_2/ak-47-point-disarray-(well-worn).png?v=4",
  "AK-47|Searing Rage|FT": "https://casesimulator.eu/skins/ak-47-searing-rage-field-tested.webp",
  "AK-47|Wild Lotus|BS": "https://cdn.g4skins.com/items/730_2/ak-47-wild-lotus-(battle-scarred).png?v=4",
  "AUG|Amber Slipstream|FT": "https://cdn.g4skins.com/items/730_2/aug-amber-slipstream-(field-tested).png?v=4",
  "AUG|Triqua|FT": "https://cdn.g4skins.com/items/730_2/aug-triqua-(field-tested).png?v=4",
  "AWP|Containment Breach|FN": "https://cdn.g4skins.com/items/730_2/awp-containment-breach-(factory-new).png?v=4",
  "AWP|Corticera|FT": "https://cdn.g4skins.com/items/730_2/awp-corticera-(field-tested).png?v=4",
  "AWP|Desert Hydra|FN": "https://cdn.g4skins.com/items/730_2/awp-desert-hydra-(factory-new).png?v=4",
  "AWP|Dragon Lore|FN": "https://cdn.g4skins.com/items/730_2/awp-dragon-lore-(factory-new).png?v=4",
  "AWP|Fade|FN": "https://cdn.g4skins.com/items/730_2/awp-fade-(factory-new).png?v=4",
  "AWP|Green Energy|FN": "https://cdn.g4skins.com/items/730_2/awp-green-energy-(factory-new).png?v=4",
  "AWP|Gungnir|FN": "https://cdn.g4skins.com/items/730_2/awp-gungnir-(factory-new).png?v=4",
  "AWP|Oni Taiji|MW": "https://casesimulator.eu/skins/awp-oni-taiji-minimal-wear.webp",
  "AWP|Phobos|FT": "https://cdn.g4skins.com/items/730_2/awp-phobos-(field-tested).png?v=4",
  "AWP|Pink DDPAT|FT": "https://cdn.g4skins.com/items/730_2/awp-pink-ddpat-(field-tested).png?v=4",
  "AWP|Pit Viper|FT": "https://cdn.g4skins.com/items/730_2/awp-pit-viper-(field-tested).png?v=4",
  "AWP|Pit Viper|MW": "https://cdn.g4skins.com/items/730_2/awp-pit-viper-(minimal-wear).png?v=4",
  "AWP|Printstream|FN": "https://cdn.g4skins.com/items/730_2/awp-printstream-(factory-new).png?v=4",
  "AWP|Printstream|FT": "https://cdn.g4skins.com/items/730_2/awp-printstream-(field-tested).png?v=4",
  "AWP|Printstream|MW": "https://cdn.g4skins.com/items/730_2/awp-printstream-(minimal-wear).png?v=4",
  "AWP|The Prince|FT": "https://cdn.g4skins.com/items/730_2/awp-the-prince-(field-tested).png?v=4",
  "AWP|Wildfire|BS": "https://casesimulator.eu/skins/awp-wildfire-battle-scarred.webp",
  "AWP|Worm God|FT": "https://cdn.g4skins.com/items/730_2/awp-worm-god-(field-tested).png?v=4",
  "AWP|Worm God|MW": "https://cdn.g4skins.com/items/730_2/awp-worm-god-(minimal-wear).png?v=4",
  "Bayonet|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-bayonet-doppler-black-pearl-(factory-new).png?v=4",
  "Bayonet|Gamma Doppler Emerald|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-bayonet-gamma-doppler-emerald-(factory-new).png?v=4",
  "Butterfly Knife|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-butterfly-knife-doppler-black-pearl-(factory-new).png?v=4",
  "Butterfly Knife|Fade|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-butterfly-knife-fade-(factory-new).png?v=4",
  "Butterfly Knife|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1Z-ua6bbZrLOmsD2qvxONzouBlSxa-lA8lvziMgIr9HifOOV5kFJp2Ee9b4Rntm4GxY7_ntQHc2o1DmH6r3Hgcv3w4t-pXU6ZzrPHQjQnfcepq0dwfRJw",
  "Butterfly Knife|Gamma Doppler Phase 2|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1Z-ua6bbZrLOmsD2qvxu97veBWSyajhREioQKVko7qJHn4Ml93UtZuF-AK4USwmtS2Nei05w2NjNoQzCX9iXwavHo-57oKVfFw__GFjVvGNKp9v8f8XHnkNg",
  "Butterfly Knife|Lore|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-butterfly-knife-lore-(factory-new).png?v=4",
  "Bowie Knife|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-bowie-knife-doppler-black-pearl-(factory-new).png?v=4",
  "Bowie Knife|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1I-uC4YbJsLM-RAXCZxNF3vd5sQiyhlBEjjDCEiI31JCLdO1JPVssnHaMU4EG-ltyyPuLq5gHYj9lMzyz7hyxNuCs-5OoDVKImrKTe21mXZ-Zu5I5Deqhh5Zn_hA",
  "Classic Knife|Fade|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-classic-knife-fade-(factory-new).png?v=4",
  "CZ75-Auto|Emerald|FN": "https://cdn.g4skins.com/items/730_2/cz75-auto-emerald-(factory-new).png?v=4",
  "CZ75-Auto|Hexane|FN": "https://cdn.g4skins.com/items/730_2/cz75-auto-hexane-(factory-new).png?v=4",
  "CZ75-Auto|Pole Position|FT": "https://cdn.g4skins.com/items/730_2/cz75-auto-pole-position-(field-tested).png?v=4",
  "CZ75-Auto|Pole Position|MW": "https://cdn.g4skins.com/items/730_2/cz75-auto-pole-position-(minimal-wear).png?v=4",
  "CZ75-Auto|Tacticat|FT": "https://cdn.g4skins.com/items/730_2/cz75-auto-tacticat-(field-tested).png?v=4",
  "CZ75-Auto|The Fuschia Is Now|FT": "https://cdn.g4skins.com/items/730_2/cz75-auto-the-fuschia-is-now-(field-tested).png?v=4",
  "CZ75-Auto|Tigris|FT": "https://cdn.g4skins.com/items/730_2/cz75-auto-tigris-(field-tested).png?v=4",
  "CZ75-Auto|Tigris|MW": "https://cdn.g4skins.com/items/730_2/cz75-auto-tigris-(minimal-wear).png?v=4",
  "CZ75-Auto|Victoria|WW": "https://cdn.g4skins.com/items/730_2/cz75-auto-victoria-(well-worn).png?v=4",
  "Desert Eagle|Blaze|FN": "https://cdn.g4skins.com/items/730_2/desert-eagle-blaze-(factory-new).png?v=4",
  "Desert Eagle|Crimson Web|FT": "https://cdn.g4skins.com/items/730_2/desert-eagle-crimson-web-(field-tested).png?v=4",
  "Desert Eagle|Golden Koi|FN": "https://cdn.g4skins.com/items/730_2/desert-eagle-golden-koi-(factory-new).png?v=4",
  "Desert Eagle|Heirloom|WW": "https://cdn.g4skins.com/items/730_2/desert-eagle-heirloom-(well-worn).png?v=4",
  "Desert Eagle|Midnight Storm|BS": "https://cdn.g4skins.com/items/730_2/desert-eagle-midnight-storm-(battle-scarred).png?v=4",
  "Desert Eagle|Mint Fan|FT": "https://cdn.g4skins.com/items/730_2/desert-eagle-mint-fan-(field-tested).png?v=4",
  "Desert Eagle|Ocean Drive|WW": "https://cdn.g4skins.com/items/730_2/desert-eagle-ocean-drive-(well-worn).png?v=4",
  "Desert Eagle|Oxide Blaze|FT": "https://cdn.g4skins.com/items/730_2/desert-eagle-oxide-blaze-(field-tested).png?v=4",
  "Desert Eagle|Printstream|FN": "https://cdn.g4skins.com/items/730_2/desert-eagle-printstream-(factory-new).png?v=4",
  "Desert Eagle|Printstream|FT": "https://cdn.g4skins.com/items/730_2/desert-eagle-printstream-(field-tested).png?v=4",
  "Desert Eagle|Printstream|MW": "https://cdn.g4skins.com/items/730_2/desert-eagle-printstream-(minimal-wear).png?v=4",
  "Desert Eagle|Sunset Storm 弐|FT": "https://cdn.g4skins.com/items/730_2/desert-eagle-sunset-storm-%E5%BC%90-(field-tested).png?v=4",
  "Desert Eagle|Urban Rubble|FT": "https://cdn.g4skins.com/items/730_2/desert-eagle-urban-rubble-(field-tested).png?v=4",
  "Desert Eagle|Urban Rubble|WW": "https://cdn.g4skins.com/items/730_2/desert-eagle-urban-rubble-(well-worn).png?v=4",
  "Dual Berettas|Emerald|FN": "https://cdn.g4skins.com/items/730_2/dual-berettas-emerald-(factory-new).png?v=4",
  "Dual Berettas|Flora Carnivora|FT": "https://cdn.g4skins.com/items/730_2/dual-berettas-flora-carnivora-(field-tested).png?v=4",
  "Falchion Knife|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-falchion-knife-doppler-black-pearl-(factory-new).png?v=4",
  "Falchion Knife|Gamma Doppler Emerald|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-falchion-knife-gamma-doppler-emerald-(factory-new).png?v=4",
  "FAMAS|Commemoration|FT": "https://cdn.g4skins.com/items/730_2/famas-commemoration-(field-tested).png?v=4",
  "FAMAS|Eye of Athena|FT": "https://cdn.g4skins.com/items/730_2/famas-eye-of-athena-(field-tested).png?v=4",
  "FAMAS|Hexane|FT": "https://cdn.g4skins.com/items/730_2/famas-hexane-(field-tested).png?v=4",
  "FAMAS|Neural Net|FT": "https://cdn.g4skins.com/items/730_2/famas-neural-net-(field-tested).png?v=4",
  "FAMAS|Styx|FT": "https://casesimulator.eu/skins/famas-styx-field-tested.webp",
  "FAMAS|Styx|MW": "https://cdn.g4skins.com/items/730_2/famas-styx-(minimal-wear).png?v=4",
  "FAMAS|Survivor Z|FT": "https://cdn.g4skins.com/items/730_2/famas-survivor-z-(field-tested).png?v=4",
  "FAMAS|Waters of Nephthys|FT": "https://cdn.g4skins.com/items/730_2/famas-waters-of-nephthys-(field-tested).png?v=4",
  "Five-SeveN|Buddy|FT": "https://cdn.g4skins.com/items/730_2/five-seven-buddy-(field-tested).png?v=4",
  "Five-SeveN|Capillary|FT": "https://cdn.g4skins.com/items/730_2/five-seven-capillary-(field-tested).png?v=4",
  "Five-SeveN|Case Hardened|FT": "https://cdn.g4skins.com/items/730_2/five-seven-case-hardened-(field-tested).png?v=4",
  "Five-SeveN|Copper Galaxy|FT": "https://cdn.g4skins.com/items/730_2/five-seven-copper-galaxy-(field-tested).png?v=4",
  "Five-SeveN|Crimson Blossom|MW": "https://cdn.g4skins.com/items/730_2/five-seven-crimson-blossom-(minimal-wear).png?v=4",
  "Five-SeveN|Fairy Tale|MW": "https://cdn.g4skins.com/items/730_2/five-seven-fairy-tale-(minimal-wear).png?v=4",
  "Five-SeveN|Fraise Crane|MW": "https://cdn.g4skins.com/items/730_2/five-seven-fraise-crane-(minimal-wear).png?v=4",
  "Five-SeveN|Scumbria|BS": "https://cdn.g4skins.com/items/730_2/five-seven-scumbria-(battle-scarred).png?v=4",
  "Five-SeveN|Urban Hazard|MW": "https://cdn.g4skins.com/items/730_2/five-seven-urban-hazard-(minimal-wear).png?v=4",
  "Flip Knife|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-flip-knife-doppler-black-pearl-(factory-new).png?v=4",
  "Flip Knife|Gamma Doppler Emerald|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-flip-knife-gamma-doppler-emerald-(factory-new).png?v=4",
  "G3SG1|Dream Glade|FT": "https://cdn.g4skins.com/items/730_2/g3sg1-dream-glade-(field-tested).png?v=4",
  "G3SG1|Orange Crash|FN": "https://cdn.g4skins.com/items/730_2/g3sg1-orange-crash-(factory-new).png?v=4",
  "G3SG1|Orange Crash|FT": "https://cdn.g4skins.com/items/730_2/g3sg1-orange-crash-(field-tested).png?v=4",
  "Galil AR|Aqua Terrace|FT": "https://cdn.g4skins.com/items/730_2/galil-ar-aqua-terrace-(field-tested).png?v=4",
  "Galil AR|Galigator|FT": "https://cdn.g4skins.com/items/730_2/galil-ar-galigator-(field-tested).png?v=4",
  "Galil AR|Phoenix Blacklight|FN": "https://cdn.g4skins.com/items/730_2/galil-ar-phoenix-blacklight-(factory-new).png?v=4",
  "Galil AR|Phoenix Blacklight|FT": "https://cdn.g4skins.com/items/730_2/galil-ar-phoenix-blacklight-(field-tested).png?v=4",
  "Galil AR|Rocket Pop|FT": "https://cdn.g4skins.com/items/730_2/galil-ar-rocket-pop-(field-tested).png?v=4",
  "Galil AR|Sandstorm|FT": "https://cdn.g4skins.com/items/730_2/galil-ar-sandstorm-(field-tested).png?v=4",
  "Galil AR|Sky Mandala|FT": "https://cdn.g4skins.com/items/730_2/galil-ar-sky-mandala-(field-tested).png?v=4",
  "Galil AR|Stone Cold|FT": "https://cdn.g4skins.com/items/730_2/galil-ar-stone-cold-(field-tested).png?v=4",
  "Glock-18|AXIA|FN": "https://cdn.g4skins.com/items/730_2/glock-18-axia-(factory-new).png?v=4",
  "Glock-18|Brass|WW": "https://cdn.g4skins.com/items/730_2/glock-18-brass-(well-worn).png?v=4",
  "Glock-18|Bunsen Burner|FT": "https://cdn.g4skins.com/items/730_2/glock-18-bunsen-burner-(field-tested).png?v=4",
  "Glock-18|Catacombs|FT": "https://cdn.g4skins.com/items/730_2/glock-18-catacombs-(field-tested).png?v=4",
  "Glock-18|Fade|FN": "https://cdn.g4skins.com/items/730_2/glock-18-fade-(factory-new).png?v=4",
  "Glock-18|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL2kpnj9h1a4s2rZaF_IfyXMWqR0-x6tehzSi2MkhEosDa6lob-KT-JPwZzA5J4F-8Mt0a-ktTvNeyws1PfjIsQyiX9h3gYvSpr5bwFWash-7qX0V9IgS2WPw",
  "Glock-18|Moonrise|FT": "https://cdn.g4skins.com/items/730_2/glock-18-moonrise-(field-tested).png?v=4",
  "Glock-18|Moonrise|MW": "https://cdn.g4skins.com/items/730_2/glock-18-moonrise-(minimal-wear).png?v=4",
  "Glock-18|Ocean Topo|FN": "https://cdn.g4skins.com/items/730_2/glock-18-ocean-topo-(factory-new).png?v=4",
  "Glock-18|Off World|FT": "https://cdn.g4skins.com/items/730_2/glock-18-off-world-(field-tested).png?v=4",
  "Glock-18|Ramese's Reach|FT": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL2kpnj9h1Y-s2pZKtuK8-BD2qKxP1JveRtRjy-2x9wsGqBzI2rcy-SOwVyX8R5ELEIsUPtktW1MO6w4AbejNlGmCn623xXrnE88DgT8mI",
  "Glock-18|Synth Leaf|FT": "https://cdn.g4skins.com/items/730_2/glock-18-synth-leaf-(field-tested).png?v=4",
  "Glock-18|Vogue|FT": "https://cdn.g4skins.com/items/730_2/glock-18-vogue-(field-tested).png?v=4",
  "Glock-18|Warhawk|MW": "https://cdn.g4skins.com/items/730_2/glock-18-warhawk-(minimal-wear).png?v=4",
  "Glock-18|Water Elemental|MW": "https://cdn.g4skins.com/items/730_2/glock-18-water-elemental-(minimal-wear).png?v=4",
  "Glock-18|Weasel|FT": "https://cdn.g4skins.com/items/730_2/glock-18-weasel-(field-tested).png?v=4",
  "Glock-18|Weasel|MW": "https://cdn.g4skins.com/items/730_2/glock-18-weasel-(minimal-wear).png?v=4",
  "Gut Knife|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-gut-knife-doppler-black-pearl-(factory-new).png?v=4",
  "Gut Knife|Fade|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-gut-knife-fade-(factory-new).png?v=4",
  "Gut Knife|Gamma Doppler Emerald|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-gut-knife-gamma-doppler-emerald-(factory-new).png?v=4",
  "Gut Knife|Gamma Doppler Phase 1|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-gut-knife-gamma-doppler-(factory-new).png?v=4",
  "Hand Wraps|CAUTION!|FT": "https://cdn.g4skins.com/items/730_2/%E2%98%85-hand-wraps-caution!-(field-tested).png?v=4",
  "Hand Wraps|Cobalt Skulls|WW": "https://cdn.g4skins.com/items/730_2/%E2%98%85-hand-wraps-cobalt-skulls-(well-worn).png?v=4",
  "Hand Wraps|Desert Shamagh|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-hand-wraps-desert-shamagh-(factory-new).png?v=4",
  "Huntsman Knife|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-huntsman-knife-doppler-black-pearl-(factory-new).png?v=4",
  "Huntsman Knife|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpovbSsLQJfx_LLZTRB7dCJlY20kvrxIbrdklRc6ddzhuzI74nxt1i9rBsofWD2IIDDcFQ9MwvV-FO5xejngpK16c6bmyZguiUj7HqMnRfjhBhOOOJxxavJeVUN3dA",
  "Karambit|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-karambit-doppler-black-pearl-(factory-new).png?v=4",
  "Karambit|Fade|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-karambit-fade-(factory-new).png?v=4",
  "Karambit|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1Q7uCvZaZkNM-SA1iVzOtkse1tcCSyhx8rtjSfn4vGLSLANkI-X8MjTLFYskTsw9bnZOuwsgSIj4sTniz-2i5A7yY6tbwGV6Nx-qGEjxaBb-MuPavopw",
  "Karambit|Lore|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-karambit-lore-(factory-new).png?v=4",
  "Karambit|Tiger Tooth|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-karambit-tiger-tooth-(factory-new).png?v=4",
  "M249|Emerald Poison Dart|FN": "https://cdn.g4skins.com/items/730_2/m249-emerald-poison-dart-(factory-new).png?v=4",
  "M249|System Lock|WW": "https://cdn.g4skins.com/items/730_2/m249-system-lock-(well-worn).png?v=4",
  "M4A1-S|Basilisk|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-basilisk-(field-tested).png?v=4",
  "M4A1-S|Basilisk|MW": "https://cdn.g4skins.com/items/730_2/m4a1-s-basilisk-(minimal-wear).png?v=4",
  "M4A1-S|Black Lotus|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-black-lotus-(field-tested).png?v=4",
  "M4A1-S|Black Lotus|MW": "https://cdn.g4skins.com/items/730_2/m4a1-s-black-lotus-(minimal-wear).png?v=4",
  "M4A1-S|Blood Tiger|MW": "https://cdn.g4skins.com/items/730_2/m4a1-s-blood-tiger-(minimal-wear).png?v=4",
  "M4A1-S|Briefing|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-briefing-(field-tested).png?v=4",
  "M4A1-S|Bright Water|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-bright-water-(field-tested).png?v=4",
  "M4A1-S|Chantico's Fire|FT": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL8ypexwjFS4_ega6F_H_OGMWrEwL9lj_JmWiWnlBYioQKIn4vwNCaJaAUmX8AjRuFb5BO-xNzvMb-34FbYg41HxC7-3C1LuCo_4ulUVPAnrLqX0V_9LjFL0A",
  "M4A1-S|Dark Water|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-dark-water-(field-tested).png?v=4",
  "M4A1-S|Decimator|FN": "https://cdn.g4skins.com/items/730_2/m4a1-s-decimator-(factory-new).png?v=4",
  "M4A1-S|Fade|FN": "https://cdn.g4skins.com/items/730_2/m4a1-s-fade-(factory-new).png?v=4",
  "M4A1-S|Flashback|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-flashback-(field-tested).png?v=4",
  "M4A1-S|Flashback|WW": "https://cdn.g4skins.com/items/730_2/m4a1-s-flashback-(well-worn).png?v=4",
  "M4A1-S|Golden Coil|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-golden-coil-(field-tested).png?v=4",
  "M4A1-S|Icarus Fell|FN": "https://cdn.g4skins.com/items/730_2/m4a1-s-icarus-fell-(factory-new).png?v=4",
  "M4A1-S|Master Piece|BS": "https://cdn.g4skins.com/items/730_2/m4a1-s-master-piece-(battle-scarred).png?v=4",
  "M4A1-S|Nightmare|WW": "https://cdn.g4skins.com/items/730_2/m4a1-s-nightmare-(well-worn).png?v=4",
  "M4A1-S|Nitro|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-nitro-(field-tested).png?v=4",
  "M4A1-S|Printstream|FN": "https://cdn.g4skins.com/items/730_2/m4a1-s-printstream-(factory-new).png?v=4",
  "M4A1-S|Printstream|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-printstream-(field-tested).png?v=4",
  "M4A1-S|Printstream|MW": "https://cdn.g4skins.com/items/730_2/m4a1-s-printstream-(minimal-wear).png?v=4",
  "M4A4|Evil Daimyo|FT": "https://cdn.g4skins.com/items/730_2/m4a4-evil-daimyo-(field-tested).png?v=4",
  "M4A4|Eye of Horus|FN": "https://cdn.g4skins.com/items/730_2/m4a4-eye-of-horus-(factory-new).png?v=4",
  "M4A4|Griffin|FT": "https://cdn.g4skins.com/items/730_2/m4a4-griffin-(field-tested).png?v=4",
  "M4A4|Hellfire|FN": "https://casesimulator.eu/skins/m4a4-hellfire-factory-new.webp",
  "M4A4|Hellish|FT": "https://casesimulator.eu/skins/m4a4-hellish-field-tested.webp",
  "M4A4|Howl|FN": "https://casesimulator.eu/skins/m4a4-howl-factory-new.webp",
  "M4A4|Royal Paladin|FT": "https://cdn.g4skins.com/items/730_2/m4a4-royal-paladin-(field-tested).png?v=4",
  "M4A4|Temukau|FT": "https://cdn.g4skins.com/items/730_2/m4a4-temukau-(field-tested).png?v=4",
  "M4A4|The Emperor|FT": "https://cdn.g4skins.com/items/730_2/m4a4-the-emperor-(field-tested).png?v=4",
  "M9 Bayonet|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-m9-bayonet-doppler-black-pearl-(factory-new).png?v=4",
  "M9 Bayonet|Fade|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-m9-bayonet-fade-(factory-new).png?v=4",
  "M9 Bayonet|Gamma Doppler Emerald|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-m9-bayonet-gamma-doppler-emerald-(factory-new).png?v=4",
  "M9 Bayonet|Lore|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-m9-bayonet-lore-(factory-new).png?v=4",
  "MAC-10|Amber Fade|MW": "https://cdn.g4skins.com/items/730_2/mac-10-amber-fade-(minimal-wear).png?v=4",
  "MAC-10|Classic Crate|FT": "https://cdn.g4skins.com/items/730_2/mac-10-classic-crate-(field-tested).png?v=4",
  "MAC-10|Fade|FN": "https://cdn.g4skins.com/items/730_2/mac-10-fade-(factory-new).png?v=4",
  "MAC-10|Gold Brick|FT": "https://cdn.g4skins.com/items/730_2/mac-10-gold-brick-(field-tested).png?v=4",
  "MAC-10|Oceanic|FT": "https://cdn.g4skins.com/items/730_2/mac-10-oceanic-(field-tested).png?v=4",
  "MAC-10|Saibā Oni|FT": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL8n5WxrR1W7vH_OJtiOvGYB1icyOl-pK89HXuxkRt2627Syt2udn6TZlJyW5R0QuMKsRm6lNflNO3g7lfbi49H02yg2Yk7YeQ4",
  "MAC-10|Toybox|FT": "https://cdn.g4skins.com/items/730_2/mac-10-toybox-(field-tested).png?v=4",
  "MAC-10|Ultraviolet|FT": "https://cdn.g4skins.com/items/730_2/mac-10-ultraviolet-(field-tested).png?v=4",
  "MAG-7|Counter Terrace|MW": "https://cdn.g4skins.com/items/730_2/mag-7-counter-terrace-(minimal-wear).png?v=4",
  "MAG-7|Sand Dune|BS": "https://cdn.g4skins.com/items/730_2/mag-7-sand-dune-(battle-scarred).png?v=4",
  "MAG-7|SWAG-7|FT": "https://cdn.g4skins.com/items/730_2/mag-7-swag-7-(field-tested).png?v=4",
  "MAG-7|Wildwood|FT": "https://cdn.g4skins.com/items/730_2/mag-7-wildwood-(field-tested).png?v=4",
  "Moto Gloves|Spearmint|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-moto-gloves-spearmint-(factory-new).png?v=4",
  "MP5-SD|Co-Processor|MW": "https://cdn.g4skins.com/items/730_2/mp5-sd-co-processor-(minimal-wear).png?v=4",
  "MP5-SD|Savannah Halftone|WW": "https://cdn.g4skins.com/items/730_2/mp5-sd-savannah-halftone-(well-worn).png?v=4",
  "MP7|Akoben|FT": "https://cdn.g4skins.com/items/730_2/mp7-akoben-(field-tested).png?v=4",
  "MP7|Amberline|FT": "https://cdn.g4skins.com/items/730_2/mp7-amberline-(field-tested).png?v=4",
  "MP7|Cirrus|FT": "https://cdn.g4skins.com/items/730_2/mp7-cirrus-(field-tested).png?v=4",
  "MP7|Nemesis|MW": "https://cdn.g4skins.com/items/730_2/mp7-nemesis-(minimal-wear).png?v=4",
  "MP7|Ocean Foam|MW": "https://cdn.g4skins.com/items/730_2/mp7-ocean-foam-(minimal-wear).png?v=4",
  "MP7|Special Delivery|FT": "https://cdn.g4skins.com/items/730_2/mp7-special-delivery-(field-tested).png?v=4",
  "MP7|Urban Hazard|FN": "https://cdn.g4skins.com/items/730_2/mp7-urban-hazard-(factory-new).png?v=4",
  "MP9|Black Sand|FT": "https://cdn.g4skins.com/items/730_2/mp9-black-sand-(field-tested).png?v=4",
  "MP9|Mount Fuji|BS": "https://cdn.g4skins.com/items/730_2/mp9-mount-fuji-(battle-scarred).png?v=4",
  "MP9|Ruby Poison Dart|FT": "https://casesimulator.eu/skins/mp9-ruby-poison-dart-field-tested.webp",
  "MP9|Sand Dashed|FT": "https://cdn.g4skins.com/items/730_2/mp9-sand-dashed-(field-tested).png?v=4",
  "MP9|Setting Sun|FT": "https://cdn.g4skins.com/items/730_2/mp9-setting-sun-(field-tested).png?v=4",
  "MP9|Wild Lily|FN": "https://cdn.g4skins.com/items/730_2/mp9-wild-lily-(factory-new).png?v=4",
  "Navaja Knife|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-navaja-knife-doppler-black-pearl-(factory-new).png?v=4",
  "Negev|Loudmouth|FT": "https://cdn.g4skins.com/items/730_2/negev-loudmouth-(field-tested).png?v=4",
  "Negev|Mjölnir|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL_m5Hl6x1c_M2gbaNoNs-HBmiC_uJ_t-l9AXDhxRsi62yEmYqrdSmSbQMhWcN3EO8KshHpw4LmP-Oz51bcjNgXn3ngznQe6IKqifc",
  "Negev|Power Loader|WW": "https://cdn.g4skins.com/items/730_2/negev-power-loader-(well-worn).png?v=4",
  "Nomad Knife|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-nomad-knife-doppler-black-pearl-(factory-new).png?v=4",
  "P2000|Fire Elemental|FT": "https://casesimulator.eu/skins/p2000-fire-elemental-field-tested.webp",
  "P2000|Ocean Foam|FN": "https://cdn.g4skins.com/items/730_2/p2000-ocean-foam-(factory-new).png?v=4",
  "P2000|Oceanic|FT": "https://cdn.g4skins.com/items/730_2/p2000-oceanic-(field-tested).png?v=4",
  "P2000|Oceanic|MW": "https://cdn.g4skins.com/items/730_2/p2000-oceanic-(minimal-wear).png?v=4",
  "P2000|Royal Baroque|FN": "https://cdn.g4skins.com/items/730_2/p2000-royal-baroque-(factory-new).png?v=4",
  "P250|Apep's Curse|FT": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLhzMOwwiVI0OL8PfRSIeCWHlidxOp_pewnGnm2kRh06z-GytyqdnifbgQgXJJ3Q7VfskbslYbnMezl5lGL2owQxTK-0H2PNN-2XA",
  "P250|Sand Dune|FT": "https://cdn.g4skins.com/items/730_2/p250-sand-dune-(field-tested).png?v=4",
  "P250|Supernova|FT": "https://cdn.g4skins.com/items/730_2/p250-supernova-(field-tested).png?v=4",
  "P250|Valence|FT": "https://cdn.g4skins.com/items/730_2/p250-valence-(field-tested).png?v=4",
  "P250|Vino Primo|FT": "https://cdn.g4skins.com/items/730_2/p250-vino-primo-(field-tested).png?v=4",
  "P250|Wingshot|FT": "https://cdn.g4skins.com/items/730_2/p250-wingshot-(field-tested).png?v=4",
  "P90|Astral Jörmungandr|MW": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLhx8bf_C9k5f28ZZtvLOWWMWuZxuZi_rJtFiziwkom4GXTyNqrIC-TPVMgApAkE-EMtUS-xoCzNry35Fff3t5bjXKprRMe7_8",
  "P90|Chopper|FT": "https://cdn.g4skins.com/items/730_2/p90-chopper-(field-tested).png?v=4",
  "P90|Chopper|MW": "https://cdn.g4skins.com/items/730_2/p90-chopper-(minimal-wear).png?v=4",
  "P90|Elite Build|FT": "https://cdn.g4skins.com/items/730_2/p90-elite-build-(field-tested).png?v=4",
  "P90|Facility Negative|MW": "https://cdn.g4skins.com/items/730_2/p90-facility-negative-(minimal-wear).png?v=4",
  "P90|Grim|FT": "https://cdn.g4skins.com/items/730_2/p90-grim-(field-tested).png?v=4",
  "P90|ScaraB Rush|WW": "https://cdn.g4skins.com/items/730_2/p90-scarab-rush-(well-worn).png?v=4",
  "Paracord Knife|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-paracord-knife-doppler-black-pearl-(factory-new).png?v=4",
  "PP-Bizon|Antique|FT": "https://cdn.g4skins.com/items/730_2/pp-bizon-antique-(field-tested).png?v=4",
  "PP-Bizon|Jungle Slipstream|FT": "https://cdn.g4skins.com/items/730_2/pp-bizon-jungle-slipstream-(field-tested).png?v=4",
  "R8 Revolver|Crimson Web|BS": "https://cdn.g4skins.com/items/730_2/r8-revolver-crimson-web-(battle-scarred).png?v=4",
  "Sawed-Off|Kiss♥Love|FT": "https://cdn.g4skins.com/items/730_2/sawed-off-kiss%E2%99%A5love-(field-tested).png?v=4",
  "Sawed-Off|The Kraken|MW": "https://cdn.g4skins.com/items/730_2/sawed-off-the-kraken-(minimal-wear).png?v=4",
  "SCAR-20|Blueprint|MW": "https://cdn.g4skins.com/items/730_2/scar-20-blueprint-(minimal-wear).png?v=4",
  "Shadow Daggers|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpovbSsLQJfw-bbeQJD4eOzmYWZlvvwDLbQhGld7cxrj-3--YXygED6-0VsYz-hJNKcIwM8aQ3XqFi7l7_ngpHquJ7LyyZl6SQg5iqInRK0hQYMMLJWkXxH2Q",
  "SG 553|Aerial|WW": "https://cdn.g4skins.com/items/730_2/sg-553-aerial-(well-worn).png?v=4",
  "SG 553|Colony IV|FT": "https://cdn.g4skins.com/items/730_2/sg-553-colony-iv-(field-tested).png?v=4",
  "SG 553|Triarch|FT": "https://cdn.g4skins.com/items/730_2/sg-553-triarch-(field-tested).png?v=4",
  "SSG 08|Abyss|FT": "https://cdn.g4skins.com/items/730_2/ssg-08-abyss-(field-tested).png?v=4",
  "SSG 08|Big Iron|FT": "https://cdn.g4skins.com/items/730_2/ssg-08-big-iron-(field-tested).png?v=4",
  "SSG 08|Dragonfire|FN": "https://casesimulator.eu/skins/ssg-08-dragonfire-factory-new.webp",
  "SSG 08|Ghost Crusader|FT": "https://cdn.g4skins.com/items/730_2/ssg-08-ghost-crusader-(field-tested).png?v=4",
  "SSG 08|Slashed|WW": "https://cdn.g4skins.com/items/730_2/ssg-08-slashed-(well-worn).png?v=4",
  "Skeleton Knife|Slaughter|FN": "https://casesimulator.eu/skins/skeleton-knife-slaughter-factory-new.webp",
  "Sport Gloves|Slingshot|MW": "https://casesimulator.eu/skins/sport-gloves-slingshot-minimal-wear.webp",
  "Sport Gloves|Vice|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-sport-gloves-vice-(factory-new).png?v=4",
  "Sport Gloves|Violet Beadwork|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-sport-gloves-violet-beadwork-(factory-new).png?v=4",
  "Sticker|Lorena (Holo)|-": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjMmuOHaC619h7cjn_17mUxvwnZOysipU4_2RZKt_Jf6SQD_EwL8v6Oc6HSvnxxtx5G3dnNardnKTOlMjCMRwTbQLtRW8x9TgYun8p1uJzJlv4Fg",
  "Sticker|Nelu the Bear|-": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjMmuOHaC619h7dempVfiTQjllpPi-CNJofT8MPU6dKXGWjfAk-ol5-c8SnqwwBkisGrVzI2hcXiUa1QlCZsjRbYU8k7vnUZEXqM",
  "Sticker|Wildcard (Gold) | Shanghai 2024|-": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjNmpNCnHtwI644Tm7mbgThH10MXmpHADu6r5Pf1uI6nLWzKUkb134uU8Fy_ixkQk5z_VyY6sJ3qWbAY-SswnOwZXfgw",
  "Stiletto Knife|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-stiletto-knife-doppler-black-pearl-(factory-new).png?v=4",
  "Survival Knife|Doppler Black Pearl|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1Y7vyne5tsLc-RAmaTyv5zsfNlcCSyhx8rtjSfn4vGLSLANkI-CJQjFrQJsxHrktfjMu6z5gbYi49FyS-rh3lJuHxst7oLAvci-PDehxaBb-MyRwuVrw",
  "Survival Knife|Tiger Tooth|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-survival-knife-tiger-tooth-(factory-new).png?v=4",
  "Talon Knife|Doppler Ruby|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1M5vahf6lsK_WBMWad_vxjsvhWQiihlxEiuieAnrD1KCzPKhgjDJt0TOZYsEWxm9C1ZOzqtgfW3oITxS_3jntJ6y5t4-YFA6YlrvaCkUifZtYs94Eq",
  "Tec-9|Fubar|FT": "https://cdn.g4skins.com/items/730_2/tec-9-fubar-(field-tested).png?v=4",
  "Tec-9|Fuel Injector|BS": "https://cdn.g4skins.com/items/730_2/tec-9-fuel-injector-(battle-scarred).png?v=4",
  "Tec-9|Ice Cap|MW": "https://cdn.g4skins.com/items/730_2/tec-9-ice-cap-(minimal-wear).png?v=4",
  "Tec-9|Isaac|MW": "https://cdn.g4skins.com/items/730_2/tec-9-isaac-(minimal-wear).png?v=4",
  "Tec-9|Jambiya|FT": "https://cdn.g4skins.com/items/730_2/tec-9-jambiya-(field-tested).png?v=4",
  "Tec-9|Mummy's Rot|FT": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLlm5W5wiFO0Oara_1SLeWeA36vzOtyufRkAX-3lB4mtjiBzNuucnyRPVMkXsYmQ-IL4xbsmt22M77m71Ddj9kRzSrgznQeJH2Wtgg",
  "Tec-9|Sandstorm|MW": "https://cdn.g4skins.com/items/730_2/tec-9-sandstorm-(minimal-wear).png?v=4",
  "Tec-9|Terrace|FT": "https://cdn.g4skins.com/items/730_2/tec-9-terrace-(field-tested).png?v=4",
  "Tec-9|Toxic|FT": "https://cdn.g4skins.com/items/730_2/tec-9-toxic-(field-tested).png?v=4",
  "UMP-45|Arctic Wolf|FT": "https://cdn.g4skins.com/items/730_2/ump-45-arctic-wolf-(field-tested).png?v=4",
  "UMP-45|Briefing|MW": "https://cdn.g4skins.com/items/730_2/ump-45-briefing-(minimal-wear).png?v=4",
  "UMP-45|Exposure|FT": "https://cdn.g4skins.com/items/730_2/ump-45-exposure-(field-tested).png?v=4",
  "UMP-45|Labyrinth|FT": "https://cdn.g4skins.com/items/730_2/ump-45-labyrinth-(field-tested).png?v=4",
  "Ursus Knife|Doppler Black Pearl|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-ursus-knife-doppler-black-pearl-(factory-new).png?v=4",
  "USP-S|Ancient Visions|FN": "https://cdn.g4skins.com/items/730_2/usp-s-ancient-visions-(factory-new).png?v=4",
  "USP-S|Check Engine|FT": "https://cdn.g4skins.com/items/730_2/usp-s-check-engine-(field-tested).png?v=4",
  "USP-S|Cyrex|FT": "https://cdn.g4skins.com/items/730_2/usp-s-cyrex-(field-tested).png?v=4",
  "USP-S|Cyrex|MW": "https://cdn.g4skins.com/items/730_2/usp-s-cyrex-(minimal-wear).png?v=4",
  "USP-S|Guardian|FN": "https://cdn.g4skins.com/items/730_2/usp-s-guardian-(factory-new).png?v=4",
  "USP-S|Guardian|MW": "https://cdn.g4skins.com/items/730_2/usp-s-guardian-(minimal-wear).png?v=4",
  "USP-S|Jawbreaker|MW": "https://cdn.g4skins.com/items/730_2/usp-s-jawbreaker-(minimal-wear).png?v=4",
  "USP-S|Kill Confirmed|MW": "https://casesimulator.eu/skins/usp-s-kill-confirmed-minimal-wear.webp",
  "USP-S|Orange Anolis|FT": "https://cdn.g4skins.com/items/730_2/usp-s-orange-anolis-(field-tested).png?v=4",
  "USP-S|Overgrowth|FT": "https://cdn.g4skins.com/items/730_2/usp-s-overgrowth-(field-tested).png?v=4",
  "USP-S|Printstream|FN": "https://cdn.g4skins.com/items/730_2/usp-s-printstream-(factory-new).png?v=4",
  "USP-S|Printstream|FT": "https://cdn.g4skins.com/items/730_2/usp-s-printstream-(field-tested).png?v=4",
  "USP-S|Printstream|MW": "https://cdn.g4skins.com/items/730_2/usp-s-printstream-(minimal-wear).png?v=4",
  "USP-S|Purple DDPAT|FN": "https://cdn.g4skins.com/items/730_2/usp-s-purple-ddpat-(factory-new).png?v=4",
  "USP-S|Royal Guard|FT": "https://cdn.g4skins.com/items/730_2/usp-s-royal-guard-(field-tested).png?v=4",
  "USP-S|Torque|FT": "https://cdn.g4skins.com/items/730_2/usp-s-torque-(field-tested).png?v=4",
  "USP-S|Tropical Breeze|FT": "https://cdn.g4skins.com/items/730_2/usp-s-tropical-breeze-(field-tested).png?v=4",
  "Zeus x27|Earth Mandala|FT": "https://cdn.g4skins.com/items/730_2/zeus-x27-earth-mandala-(field-tested).png?v=4",
  "Zeus x27|Olympus|MW": "https://cdn.g4skins.com/items/730_2/zeus-x27-olympus-(minimal-wear).png?v=4",
  "Zeus x27|Olympus|WW": "https://cdn.g4skins.com/items/730_2/zeus-x27-olympus-(well-worn).png?v=4",
};

/* Obrazki skrzynek (ikonka widoczna w nagłówku panelu otwierania),
   kluczem jest CASE_NAME użyty w danym pliku skrzynki. */
const CASE_IMAGES = {
  "Dirt Case": "dirt_case.png",
  "Iron Case": "iron_case.png",
  "Gold Case": "gold_case.png",
  "Ultra Case": "ultra_case.png",
  "Snow Case": "snow_case.png",
  "Neon Case": "neon_case.png",
  "Waste Case": "waste_case.png",
  "Jungle Case": "case_jungle.PNG",
  "Diamond Case": "case_diamond.PNG",
  "Sand Case": "case_sand.PNG",
  "Poland Case": "case_poland.PNG",
  "Cosmos Case": "case_cosmos.PNG",
};

/* Zwraca link do obrazka danego przedmiotu na podstawie broni, skina i wear. */
function getSkinImage(it){
  return SKIN_IMAGES[`${it.weapon}|${it.skin}|${it.wear}`] || "";
}

/* Zwraca link do obrazka skrzynki na podstawie jej nazwy. */
function getCaseImage(caseName){
  return CASE_IMAGES[caseName] || "";
}