/* =========================================================================
   ŹRÓDŁA OBRAZKÓW SKINÓW — WSPÓLNY PLIK
   -------------------------------------------------------------------------
   Ten plik jest wczytywany przez case_simulator.html i case_restricted.html
   (oraz każdy inny plik skrzynki, który go podepnie) zamiast trzymania
   linku do obrazka osobno w każdym przedmiocie tablicy ITEMS.

   JAK DODAĆ WŁASNE OBRAZKI:
   Wklej link (URL) lub ścieżkę do lokalnego pliku jako wartość klucza
   "Broń|Skin|Wear", np:
       "AK-47|Blue Laminate|FT": "https://example.com/ak47_blue_laminate.png",
   Klucze są posortowane alfabetycznie (broń, potem skin, potem wear) —
   zachowaj tę kolejność przy dodawaniu nowych pozycji, żeby łatwo było
   je odnaleźć.
   Puste pole ("") oznacza brak obrazka — pokaże się zastępczy napis.
   ========================================================================= */

const SKIN_IMAGES = {
  "AK-47|B the Monster|MW": "https://cdn.g4skins.com/items/730_2/ak-47-b-the-monster-(minimal-wear).png?v=4",
  "AK-47|Blue Laminate|FT": "https://cdn.g4skins.com/items/730_2/ak-47-blue-laminate-(field-tested).png?v=4",
  "AK-47|Elite Build|FT": "https://cdn.g4skins.com/items/730_2/ak-47-elite-build-(field-tested).png?v=4",
  "AK-47|Elite Build|WW": "https://cdn.g4skins.com/items/730_2/ak-47-elite-build-(well-worn).png?v=4",
  "AK-47|Emerald Pinstripe|FT": "https://cdn.g4skins.com/items/730_2/ak-47-emerald-pinstripe-(field-tested).png?v=4",
  "AK-47|Frontside Misty|WW": "https://cdn.g4skins.com/items/730_2/ak-47-frontside-misty-(well-worn).png?v=4",
  "AK-47|Neon Rider|MW": "https://cdn.g4skins.com/items/730_2/ak-47-neon-rider-(minimal-wear).png?v=4",
  "AK-47|Orbit Mk01|FT": "https://cdn.g4skins.com/items/730_2/ak-47-orbit-mk01-(field-tested).png?v=4",
  "AK-47|Point Disarray|FT": "https://cdn.g4skins.com/items/730_2/ak-47-point-disarray-(field-tested).png?v=4",
  "AK-47|Point Disarray|WW": "https://cdn.g4skins.com/items/730_2/ak-47-point-disarray-(well-worn).png?v=4",
  "AK-47|Searing Rage|FT": "https://casesimulator.eu/skins/ak-47-searing-rage-field-tested.webp",
  "AUG|Triqua|FT": "https://cdn.g4skins.com/items/730_2/aug-triqua-(field-tested).png?v=4",
  "AWP|Containment Breach|FN": "https://cdn.g4skins.com/items/730_2/awp-containment-breach-(factory-new).png?v=4",
  "AWP|Fade|FN": "https://cdn.g4skins.com/items/730_2/awp-fade-(factory-new).png?v=4",
  "AWP|Green Energy|FN": "https://cdn.g4skins.com/items/730_2/awp-green-energy-(factory-new).png?v=4",
  "AWP|Oni Taiji|MW": "https://casesimulator.eu/skins/awp-oni-taiji-minimal-wear.webp",
  "AWP|Phobos|FT": "https://cdn.g4skins.com/items/730_2/awp-phobos-(field-tested).png?v=4",
  "AWP|Pink DDPAT|FT": "https://cdn.g4skins.com/items/730_2/awp-pink-ddpat-(field-tested).png?v=4",
  "AWP|Pit Viper|FT": "https://cdn.g4skins.com/items/730_2/awp-pit-viper-(field-tested).png?v=4",
  "AWP|Pit Viper|MW": "https://cdn.g4skins.com/items/730_2/awp-pit-viper-(minimal-wear).png?v=4",
  "AWP|Printstream|FN": "https://cdn.g4skins.com/items/730_2/awp-printstream-(factory-new).png?v=4",
  "AWP|Printstream|FT": "https://cdn.g4skins.com/items/730_2/awp-printstream-(field-tested).png?v=4",
  "AWP|Printstream|MW": "https://cdn.g4skins.com/items/730_2/awp-printstream-(minimal-wear).png?v=4",
  "AWP|Wildfire|BS": "https://casesimulator.eu/skins/awp-wildfire-battle-scarred.webp",
  "AWP|Worm God|FT": "https://cdn.g4skins.com/items/730_2/awp-worm-god-(field-tested).png?v=4",
  "AWP|Worm God|MW": "https://cdn.g4skins.com/items/730_2/awp-worm-god-(minimal-wear).png?v=4",
  "Bayonet|Gamma Doppler Emerald|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-bayonet-gamma-doppler-emerald-(factory-new).png?v=4",
  "Butterfly Knife|Fade|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-butterfly-knife-fade-(factory-new).png?v=4",
  "Butterfly Knife|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1Z-ua6bbZrLOmsD2qvxONzouBlSxa-lA8lvziMgIr9HifOOV5kFJp2Ee9b4Rntm4GxY7_ntQHc2o1DmH6r3Hgcv3w4t-pXU6ZzrPHQjQnfcepq0dwfRJw",
  "Bowie Knife|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1I-uC4YbJsLM-RAXCZxNF3vd5sQiyhlBEjjDCEiI31JCLdO1JPVssnHaMU4EG-ltyyPuLq5gHYj9lMzyz7hyxNuCs-5OoDVKImrKTe21mXZ-Zu5I5Deqhh5Zn_hA",
  "Classic Knife|Fade|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-classic-knife-fade-(factory-new).png?v=4",
  "CZ75-Auto|Emerald|FN": "https://cdn.g4skins.com/items/730_2/cz75-auto-emerald-(factory-new).png?v=4",
  "CZ75-Auto|Hexane|FN": "https://cdn.g4skins.com/items/730_2/cz75-auto-hexane-(factory-new).png?v=4",
  "CZ75-Auto|Pole Position|FT": "https://cdn.g4skins.com/items/730_2/cz75-auto-pole-position-(field-tested).png?v=4",
  "CZ75-Auto|Pole Position|MW": "https://cdn.g4skins.com/items/730_2/cz75-auto-pole-position-(minimal-wear).png?v=4",
  "CZ75-Auto|Tacticat|FT": "https://cdn.g4skins.com/items/730_2/cz75-auto-tacticat-(field-tested).png?v=4",
  "CZ75-Auto|Tigris|FT": "https://cdn.g4skins.com/items/730_2/cz75-auto-tigris-(field-tested).png?v=4",
  "CZ75-Auto|Tigris|MW": "https://cdn.g4skins.com/items/730_2/cz75-auto-tigris-(minimal-wear).png?v=4",
  "Desert Eagle|Blaze|FN": "https://cdn.g4skins.com/items/730_2/desert-eagle-blaze-(factory-new).png?v=4",
  "Desert Eagle|Crimson Web|FT": "https://cdn.g4skins.com/items/730_2/desert-eagle-crimson-web-(field-tested).png?v=4",
  "Desert Eagle|Midnight Storm|BS": "https://cdn.g4skins.com/items/730_2/desert-eagle-midnight-storm-(battle-scarred).png?v=4",
  "Desert Eagle|Ocean Drive|WW": "https://cdn.g4skins.com/items/730_2/desert-eagle-ocean-drive-(well-worn).png?v=4",
  "Desert Eagle|Oxide Blaze|FT": "https://cdn.g4skins.com/items/730_2/desert-eagle-oxide-blaze-(field-tested).png?v=4",
  "Desert Eagle|Printstream|FN": "https://cdn.g4skins.com/items/730_2/desert-eagle-printstream-(factory-new).png?v=4",
  "Desert Eagle|Printstream|FT": "https://cdn.g4skins.com/items/730_2/desert-eagle-printstream-(field-tested).png?v=4",
  "Desert Eagle|Printstream|MW": "https://cdn.g4skins.com/items/730_2/desert-eagle-printstream-(minimal-wear).png?v=4",
  "Desert Eagle|Sunset Storm 弐|FT": "https://cdn.g4skins.com/items/730_2/desert-eagle-sunset-storm-%E5%BC%90-(field-tested).png?v=4",
  "Desert Eagle|Urban Rubble|FT": "https://cdn.g4skins.com/items/730_2/desert-eagle-urban-rubble-(field-tested).png?v=4",
  "Desert Eagle|Urban Rubble|WW": "https://cdn.g4skins.com/items/730_2/desert-eagle-urban-rubble-(well-worn).png?v=4",
  "Dual Berettas|Emerald|FN": "https://cdn.g4skins.com/items/730_2/dual-berettas-emerald-(factory-new).png?v=4",
  "Falchion Knife|Gamma Doppler Emerald|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-falchion-knife-gamma-doppler-emerald-(factory-new).png?v=4",
  "FAMAS|Hexane|FT": "https://cdn.g4skins.com/items/730_2/famas-hexane-(field-tested).png?v=4",
  "FAMAS|Styx|FT": "https://casesimulator.eu/skins/famas-styx-field-tested.webp",
  "FAMAS|Styx|MW": "https://cdn.g4skins.com/items/730_2/famas-styx-(minimal-wear).png?v=4",
  "FAMAS|Survivor Z|FT": "https://cdn.g4skins.com/items/730_2/famas-survivor-z-(field-tested).png?v=4",
  "FAMAS|Waters of Nephthys|FT": "https://cdn.g4skins.com/items/730_2/famas-waters-of-nephthys-(field-tested).png?v=4",
  "Five-SeveN|Capillary|FT": "https://cdn.g4skins.com/items/730_2/five-seven-capillary-(field-tested).png?v=4",
  "Five-SeveN|Case Hardened|FT": "https://cdn.g4skins.com/items/730_2/five-seven-case-hardened-(field-tested).png?v=4",
  "Five-SeveN|Crimson Blossom|MW": "https://cdn.g4skins.com/items/730_2/five-seven-crimson-blossom-(minimal-wear).png?v=4",
  "Five-SeveN|Fairy Tale|MW": "https://cdn.g4skins.com/items/730_2/five-seven-fairy-tale-(minimal-wear).png?v=4",
  "Five-SeveN|Scumbria|BS": "https://cdn.g4skins.com/items/730_2/five-seven-scumbria-(battle-scarred).png?v=4",
  "Five-SeveN|Urban Hazard|MW": "https://cdn.g4skins.com/items/730_2/five-seven-urban-hazard-(minimal-wear).png?v=4",
  "Flip Knife|Gamma Doppler Emerald|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-flip-knife-gamma-doppler-emerald-(factory-new).png?v=4",
  "G3SG1|Orange Crash|FN": "https://cdn.g4skins.com/items/730_2/g3sg1-orange-crash-(factory-new).png?v=4",
  "G3SG1|Orange Crash|FT": "https://cdn.g4skins.com/items/730_2/g3sg1-orange-crash-(field-tested).png?v=4",
  "Galil AR|Aqua Terrace|FT": "https://cdn.g4skins.com/items/730_2/galil-ar-aqua-terrace-(field-tested).png?v=4",
  "Galil AR|Phoenix Blacklight|FN": "https://cdn.g4skins.com/items/730_2/galil-ar-phoenix-blacklight-(factory-new).png?v=4",
  "Galil AR|Rocket Pop|FT": "https://cdn.g4skins.com/items/730_2/galil-ar-rocket-pop-(field-tested).png?v=4",
  "Galil AR|Sandstorm|FT": "https://cdn.g4skins.com/items/730_2/galil-ar-sandstorm-(field-tested).png?v=4",
  "Galil AR|Stone Cold|FT": "https://cdn.g4skins.com/items/730_2/galil-ar-stone-cold-(field-tested).png?v=4",
  "Glock-18|Bunsen Burner|FT": "https://cdn.g4skins.com/items/730_2/glock-18-bunsen-burner-(field-tested).png?v=4",
  "Glock-18|Catacombs|FT": "https://cdn.g4skins.com/items/730_2/glock-18-catacombs-(field-tested).png?v=4",
  "Glock-18|Fade|FN": "https://cdn.g4skins.com/items/730_2/glock-18-fade-(factory-new).png?v=4",
  "Glock-18|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL2kpnj9h1a4s2rZaF_IfyXMWqR0-x6tehzSi2MkhEosDa6lob-KT-JPwZzA5J4F-8Mt0a-ktTvNeyws1PfjIsQyiX9h3gYvSpr5bwFWash-7qX0V9IgS2WPw",
  "Glock-18|Moonrise|FT": "https://cdn.g4skins.com/items/730_2/glock-18-moonrise-(field-tested).png?v=4",
  "Glock-18|Moonrise|MW": "https://cdn.g4skins.com/items/730_2/glock-18-moonrise-(minimal-wear).png?v=4",
  "Glock-18|Ocean Topo|FN": "https://cdn.g4skins.com/items/730_2/glock-18-ocean-topo-(factory-new).png?v=4",
  "Glock-18|Off World|FT": "https://cdn.g4skins.com/items/730_2/glock-18-off-world-(field-tested).png?v=4",
  "Glock-18|Vogue|FT": "https://cdn.g4skins.com/items/730_2/glock-18-vogue-(field-tested).png?v=4",
  "Glock-18|Warhawk|MW": "https://cdn.g4skins.com/items/730_2/glock-18-warhawk-(minimal-wear).png?v=4",
  "Glock-18|Water Elemental|MW": "https://cdn.g4skins.com/items/730_2/glock-18-water-elemental-(minimal-wear).png?v=4",
  "Glock-18|Weasel|FT": "https://cdn.g4skins.com/items/730_2/glock-18-weasel-(field-tested).png?v=4",
  "Glock-18|Weasel|MW": "https://cdn.g4skins.com/items/730_2/glock-18-weasel-(minimal-wear).png?v=4",
  "Gut Knife|Fade|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-gut-knife-fade-(factory-new).png?v=4",
  "Gut Knife|Gamma Doppler Emerald|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-gut-knife-gamma-doppler-emerald-(factory-new).png?v=4",
  "Gut Knife|Gamma Doppler Phase 1|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-gut-knife-gamma-doppler-(factory-new).png?v=4",
  "Hand Wraps|CAUTION!|FT": "https://cdn.g4skins.com/items/730_2/%E2%98%85-hand-wraps-caution!-(field-tested).png?v=4",
  "Hand Wraps|Cobalt Skulls|WW": "https://cdn.g4skins.com/items/730_2/%E2%98%85-hand-wraps-cobalt-skulls-(well-worn).png?v=4",
  "Huntsman Knife|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpovbSsLQJfx_LLZTRB7dCJlY20kvrxIbrdklRc6ddzhuzI74nxt1i9rBsofWD2IIDDcFQ9MwvV-FO5xejngpK16c6bmyZguiUj7HqMnRfjhBhOOOJxxavJeVUN3dA",
  "Karambit|Fade|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-karambit-fade-(factory-new).png?v=4",
  "Karambit|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1Q7uCvZaZkNM-SA1iVzOtkse1tcCSyhx8rtjSfn4vGLSLANkI-X8MjTLFYskTsw9bnZOuwsgSIj4sTniz-2i5A7yY6tbwGV6Nx-qGEjxaBb-MuPavopw",
  "Karambit|Tiger Tooth|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-karambit-tiger-tooth-(factory-new).png?v=4",
  "M249|Emerald Poison Dart|FN": "https://cdn.g4skins.com/items/730_2/m249-emerald-poison-dart-(factory-new).png?v=4",
  "M249|System Lock|WW": "https://cdn.g4skins.com/items/730_2/m249-system-lock-(well-worn).png?v=4",
  "M4A1-S|Basilisk|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-basilisk-(field-tested).png?v=4",
  "M4A1-S|Basilisk|MW": "https://cdn.g4skins.com/items/730_2/m4a1-s-basilisk-(minimal-wear).png?v=4",
  "M4A1-S|Blood Tiger|MW": "https://cdn.g4skins.com/items/730_2/m4a1-s-blood-tiger-(minimal-wear).png?v=4",
  "M4A1-S|Briefing|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-briefing-(field-tested).png?v=4",
  "M4A1-S|Bright Water|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-bright-water-(field-tested).png?v=4",
  "M4A1-S|Dark Water|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-dark-water-(field-tested).png?v=4",
  "M4A1-S|Fade|FN": "https://cdn.g4skins.com/items/730_2/m4a1-s-fade-(factory-new).png?v=4",
  "M4A1-S|Flashback|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-flashback-(field-tested).png?v=4",
  "M4A1-S|Flashback|WW": "https://cdn.g4skins.com/items/730_2/m4a1-s-flashback-(well-worn).png?v=4",
  "M4A1-S|Icarus Fell|FN": "https://cdn.g4skins.com/items/730_2/m4a1-s-icarus-fell-(factory-new).png?v=4",
  "M4A1-S|Master Piece|BS": "https://cdn.g4skins.com/items/730_2/m4a1-s-master-piece-(battle-scarred).png?v=4",
  "M4A1-S|Nightmare|WW": "https://cdn.g4skins.com/items/730_2/m4a1-s-nightmare-(well-worn).png?v=4",
  "M4A1-S|Nitro|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-nitro-(field-tested).png?v=4",
  "M4A1-S|Printstream|FN": "https://cdn.g4skins.com/items/730_2/m4a1-s-printstream-(factory-new).png?v=4",
  "M4A1-S|Printstream|FT": "https://cdn.g4skins.com/items/730_2/m4a1-s-printstream-(field-tested).png?v=4",
  "M4A1-S|Printstream|MW": "https://cdn.g4skins.com/items/730_2/m4a1-s-printstream-(minimal-wear).png?v=4",
  "M4A4|Evil Daimyo|FT": "https://cdn.g4skins.com/items/730_2/m4a4-evil-daimyo-(field-tested).png?v=4",
  "M4A4|Griffin|FT": "https://cdn.g4skins.com/items/730_2/m4a4-griffin-(field-tested).png?v=4",
  "M4A4|Hellfire|FN": "https://casesimulator.eu/skins/m4a4-hellfire-factory-new.webp",
  "M4A4|Hellish|FT": "https://casesimulator.eu/skins/m4a4-hellish-field-tested.webp",
  "M4A4|Howl|FN": "https://casesimulator.eu/skins/m4a4-howl-factory-new.webp",
  "M4A4|Temukau|FT": "https://cdn.g4skins.com/items/730_2/m4a4-temukau-(field-tested).png?v=4",
  "M9 Bayonet|Fade|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-m9-bayonet-fade-(factory-new).png?v=4",
  "M9 Bayonet|Gamma Doppler Emerald|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-m9-bayonet-gamma-doppler-emerald-(factory-new).png?v=4",
  "MAC-10|Amber Fade|MW": "https://cdn.g4skins.com/items/730_2/mac-10-amber-fade-(minimal-wear).png?v=4",
  "MAC-10|Classic Crate|FT": "https://cdn.g4skins.com/items/730_2/mac-10-classic-crate-(field-tested).png?v=4",
  "MAC-10|Fade|FN": "https://cdn.g4skins.com/items/730_2/mac-10-fade-(factory-new).png?v=4",
  "MAC-10|Oceanic|FT": "https://cdn.g4skins.com/items/730_2/mac-10-oceanic-(field-tested).png?v=4",
  "MAC-10|Toybox|FT": "https://cdn.g4skins.com/items/730_2/mac-10-toybox-(field-tested).png?v=4",
  "MAC-10|Ultraviolet|FT": "https://cdn.g4skins.com/items/730_2/mac-10-ultraviolet-(field-tested).png?v=4",
  "MAG-7|Counter Terrace|MW": "https://cdn.g4skins.com/items/730_2/mag-7-counter-terrace-(minimal-wear).png?v=4",
  "MAG-7|SWAG-7|FT": "https://cdn.g4skins.com/items/730_2/mag-7-swag-7-(field-tested).png?v=4",
  "MP5-SD|Co-Processor|MW": "https://cdn.g4skins.com/items/730_2/mp5-sd-co-processor-(minimal-wear).png?v=4",
  "MP7|Akoben|FT": "https://cdn.g4skins.com/items/730_2/mp7-akoben-(field-tested).png?v=4",
  "MP7|Cirrus|FT": "https://cdn.g4skins.com/items/730_2/mp7-cirrus-(field-tested).png?v=4",
  "MP7|Urban Hazard|FN": "https://cdn.g4skins.com/items/730_2/mp7-urban-hazard-(factory-new).png?v=4",
  "MP9|Mount Fuji|BS": "https://cdn.g4skins.com/items/730_2/mp9-mount-fuji-(battle-scarred).png?v=4",
  "MP9|Ruby Poison Dart|FT": "https://casesimulator.eu/skins/mp9-ruby-poison-dart-field-tested.webp",
  "MP9|Setting Sun|FT": "https://cdn.g4skins.com/items/730_2/mp9-setting-sun-(field-tested).png?v=4",
  "Negev|Loudmouth|FT": "https://cdn.g4skins.com/items/730_2/negev-loudmouth-(field-tested).png?v=4",
  "Negev|Power Loader|WW": "https://cdn.g4skins.com/items/730_2/negev-power-loader-(well-worn).png?v=4",
  "P2000|Fire Elemental|FT": "https://casesimulator.eu/skins/p2000-fire-elemental-field-tested.webp",
  "P2000|Oceanic|FT": "https://cdn.g4skins.com/items/730_2/p2000-oceanic-(field-tested).png?v=4",
  "P2000|Oceanic|MW": "https://cdn.g4skins.com/items/730_2/p2000-oceanic-(minimal-wear).png?v=4",
  "P250|Supernova|FT": "https://cdn.g4skins.com/items/730_2/p250-supernova-(field-tested).png?v=4",
  "P250|Valence|FT": "https://cdn.g4skins.com/items/730_2/p250-valence-(field-tested).png?v=4",
  "P250|Wingshot|FT": "https://cdn.g4skins.com/items/730_2/p250-wingshot-(field-tested).png?v=4",
  "P90|Chopper|FT": "https://cdn.g4skins.com/items/730_2/p90-chopper-(field-tested).png?v=4",
  "P90|Chopper|MW": "https://cdn.g4skins.com/items/730_2/p90-chopper-(minimal-wear).png?v=4",
  "P90|Elite Build|FT": "https://cdn.g4skins.com/items/730_2/p90-elite-build-(field-tested).png?v=4",
  "P90|Facility Negative|MW": "https://cdn.g4skins.com/items/730_2/p90-facility-negative-(minimal-wear).png?v=4",
  "P90|Grim|FT": "https://cdn.g4skins.com/items/730_2/p90-grim-(field-tested).png?v=4",
  "P90|ScaraB Rush|WW": "https://cdn.g4skins.com/items/730_2/p90-scarab-rush-(well-worn).png?v=4",
  "PP-Bizon|Jungle Slipstream|FT": "https://cdn.g4skins.com/items/730_2/pp-bizon-jungle-slipstream-(field-tested).png?v=4",
  "R8 Revolver|Crimson Web|BS": "https://cdn.g4skins.com/items/730_2/r8-revolver-crimson-web-(battle-scarred).png?v=4",
  "Sawed-Off|Kiss♥Love|FT": "https://cdn.g4skins.com/items/730_2/sawed-off-kiss%E2%99%A5love-(field-tested).png?v=4",
  "Sawed-Off|The Kraken|MW": "https://cdn.g4skins.com/items/730_2/sawed-off-the-kraken-(minimal-wear).png?v=4",
  "SCAR-20|Blueprint|MW": "https://cdn.g4skins.com/items/730_2/scar-20-blueprint-(minimal-wear).png?v=4",
  "Shadow Daggers|Gamma Doppler Emerald|FN": "https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpovbSsLQJfw-bbeQJD4eOzmYWZlvvwDLbQhGld7cxrj-3--YXygED6-0VsYz-hJNKcIwM8aQ3XqFi7l7_ngpHquJ7LyyZl6SQg5iqInRK0hQYMMLJWkXxH2Q",
  "SG 553|Aerial|WW": "https://cdn.g4skins.com/items/730_2/sg-553-aerial-(well-worn).png?v=4",
  "SSG 08|Abyss|FT": "https://cdn.g4skins.com/items/730_2/ssg-08-abyss-(field-tested).png?v=4",
  "SSG 08|Dragonfire|FN": "https://casesimulator.eu/skins/ssg-08-dragonfire-factory-new.webp",
  "SSG 08|Ghost Crusader|FT": "https://cdn.g4skins.com/items/730_2/ssg-08-ghost-crusader-(field-tested).png?v=4",
  "SSG 08|Slashed|WW": "https://cdn.g4skins.com/items/730_2/ssg-08-slashed-(well-worn).png?v=4",
  "Skeleton Knife|Slaughter|FN": "https://casesimulator.eu/skins/skeleton-knife-slaughter-factory-new.webp",
  "Sport Gloves|Slingshot|MW": "https://casesimulator.eu/skins/sport-gloves-slingshot-minimal-wear.webp",
  "Sport Gloves|Vice|FN": "https://cdn.g4skins.com/items/730_2/%E2%98%85-sport-gloves-vice-(factory-new).png?v=4",
  "Sticker|Nelu the Bear|-": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJai0ki7VeTHjMmuOHaC619h7dempVfiTQjllpPi-CNJofT8MPU6dKXGWjfAk-ol5-c8SnqwwBkisGrVzI2hcXiUa1QlCZsjRbYU8k7vnUZEXqM",
  "Talon Knife|Doppler Ruby|FN": "https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1M5vahf6lsK_WBMWad_vxjsvhWQiihlxEiuieAnrD1KCzPKhgjDJt0TOZYsEWxm9C1ZOzqtgfW3oITxS_3jntJ6y5t4-YFA6YlrvaCkUifZtYs94Eq",
  "Tec-9|Fubar|FT": "https://cdn.g4skins.com/items/730_2/tec-9-fubar-(field-tested).png?v=4",
  "Tec-9|Fuel Injector|BS": "https://cdn.g4skins.com/items/730_2/tec-9-fuel-injector-(battle-scarred).png?v=4",
  "Tec-9|Ice Cap|MW": "https://cdn.g4skins.com/items/730_2/tec-9-ice-cap-(minimal-wear).png?v=4",
  "Tec-9|Isaac|MW": "https://cdn.g4skins.com/items/730_2/tec-9-isaac-(minimal-wear).png?v=4",
  "Tec-9|Jambiya|FT": "https://cdn.g4skins.com/items/730_2/tec-9-jambiya-(field-tested).png?v=4",
  "Tec-9|Sandstorm|MW": "https://cdn.g4skins.com/items/730_2/tec-9-sandstorm-(minimal-wear).png?v=4",
  "Tec-9|Toxic|FT": "https://cdn.g4skins.com/items/730_2/tec-9-toxic-(field-tested).png?v=4",
  "UMP-45|Arctic Wolf|FT": "https://cdn.g4skins.com/items/730_2/ump-45-arctic-wolf-(field-tested).png?v=4",
  "UMP-45|Briefing|MW": "https://cdn.g4skins.com/items/730_2/ump-45-briefing-(minimal-wear).png?v=4",
  "UMP-45|Exposure|FT": "https://cdn.g4skins.com/items/730_2/ump-45-exposure-(field-tested).png?v=4",
  "UMP-45|Labyrinth|FT": "https://cdn.g4skins.com/items/730_2/ump-45-labyrinth-(field-tested).png?v=4",
  "USP-S|Check Engine|FT": "https://cdn.g4skins.com/items/730_2/usp-s-check-engine-(field-tested).png?v=4",
  "USP-S|Cyrex|FT": "https://cdn.g4skins.com/items/730_2/usp-s-cyrex-(field-tested).png?v=4",
  "USP-S|Cyrex|MW": "https://cdn.g4skins.com/items/730_2/usp-s-cyrex-(minimal-wear).png?v=4",
  "USP-S|Guardian|FN": "https://cdn.g4skins.com/items/730_2/usp-s-guardian-(factory-new).png?v=4",
  "USP-S|Guardian|MW": "https://cdn.g4skins.com/items/730_2/usp-s-guardian-(minimal-wear).png?v=4",
  "USP-S|Jawbreaker|MW": "https://cdn.g4skins.com/items/730_2/usp-s-jawbreaker-(minimal-wear).png?v=4",
  "USP-S|Kill Confirmed|MW": "https://casesimulator.eu/skins/usp-s-kill-confirmed-minimal-wear.webp",
  "USP-S|Overgrowth|FT": "https://cdn.g4skins.com/items/730_2/usp-s-overgrowth-(field-tested).png?v=4",
  "USP-S|Printstream|FN": "https://cdn.g4skins.com/items/730_2/usp-s-printstream-(factory-new).png?v=4",
  "USP-S|Printstream|FT": "https://cdn.g4skins.com/items/730_2/usp-s-printstream-(field-tested).png?v=4",
  "USP-S|Printstream|MW": "https://cdn.g4skins.com/items/730_2/usp-s-printstream-(minimal-wear).png?v=4",
  "USP-S|Torque|FT": "https://cdn.g4skins.com/items/730_2/usp-s-torque-(field-tested).png?v=4",
  "Zeus x27|Olympus|WW": "https://cdn.g4skins.com/items/730_2/zeus-x27-olympus-(well-worn).png?v=4",
};

/* Obrazki skrzynek (ikonka widoczna w nagłówku panelu otwierania),
   kluczem jest CASE_NAME użyty w danym pliku skrzynki. */
const CASE_IMAGES = {
  "Dirt Case": "dirt_case.png",
  "Iron Case": "iron_case.png",
  "Gold Case": "gold_case.png",
  "Ultra Case": "ultra_case.png",
  "Snow Case": "snow_case.png",
  "Neon Case": "neon_case.png",
  "Waste Case": "waste_case.png",
};

/* Zwraca link do obrazka danego przedmiotu na podstawie broni, skina i wear. */
function getSkinImage(it){
  return SKIN_IMAGES[`${it.weapon}|${it.skin}|${it.wear}`] || "";
}

/* Zwraca link do obrazka skrzynki na podstawie jej nazwy. */
function getCaseImage(caseName){
  return CASE_IMAGES[caseName] || "";
}